// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    databaseURL: 'https://ecommerce-3bb9b-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyC_dmkmvBQ-IuFAX18pgmfaZiba_76QLkM',
    appId: '1:972637949213:web:78b8673fd162e536d465f4',
    messagingSenderId: '972637949213',
    projectId: 'ecommerce-3bb9b',
    authDomain: 'ecommerce-3bb9b.firebaseapp.com',
    storageBucket: 'ecommerce-3bb9b.appspot.com',
    measurementId: 'G-PMD4ZN5SS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL: 'https://ecommerce-3bb9b-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyAkXRHa-t7tYAYh7Rcki1j88kys4H0hZl0',
    appId: '1:972637949213:android:5962f1e9fc4ca5c7d465f4',
    messagingSenderId: '972637949213',
    projectId: 'ecommerce-3bb9b',
    storageBucket: 'ecommerce-3bb9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    databaseURL: 'https://ecommerce-3bb9b-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyDHdHKS4LkGtdbr8DAUVgUPm3ZExBjKRrc',
    appId: '1:972637949213:ios:df7b3ad1559d577dd465f4',
    messagingSenderId: '972637949213',
    projectId: 'ecommerce-3bb9b',
    storageBucket: 'ecommerce-3bb9b.appspot.com',
    androidClientId:
        '972637949213-lk74nqoq9ohfjdqnu35vsksqo8a5sjkq.apps.googleusercontent.com',
    iosClientId:
        '972637949213-c7a4ol4l6jm9na7ecnogin464orqfpa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    databaseURL: 'https://ecommerce-3bb9b-default-rtdb.firebaseio.com/',
    apiKey: 'AIzaSyDHdHKS4LkGtdbr8DAUVgUPm3ZExBjKRrc',
    appId: '1:972637949213:ios:b4651a03798102d1d465f4',
    messagingSenderId: '972637949213',
    projectId: 'ecommerce-3bb9b',
    storageBucket: 'ecommerce-3bb9b.appspot.com',
    androidClientId:
        '972637949213-lk74nqoq9ohfjdqnu35vsksqo8a5sjkq.apps.googleusercontent.com',
    iosClientId:
        '972637949213-srffg91cq57jc8sad9amld30qaajigj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
